// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.18.1
// source: datastruct.proto

package lndata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FragmentInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FragsetId uint64 `protobuf:"varint,1,opt,name=fragset_id,json=fragsetId,proto3" json:"fragset_id,omitempty"`
	TotalSize uint32 `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	Offset    uint32 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *FragmentInfo) Reset() {
	*x = FragmentInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datastruct_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FragmentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FragmentInfo) ProtoMessage() {}

func (x *FragmentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_datastruct_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FragmentInfo.ProtoReflect.Descriptor instead.
func (*FragmentInfo) Descriptor() ([]byte, []int) {
	return file_datastruct_proto_rawDescGZIP(), []int{0}
}

func (x *FragmentInfo) GetFragsetId() uint64 {
	if x != nil {
		return x.FragsetId
	}
	return 0
}

func (x *FragmentInfo) GetTotalSize() uint32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *FragmentInfo) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type DataStruct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version  uint32        `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Payload  []byte        `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Fragment *FragmentInfo `protobuf:"bytes,3,opt,name=fragment,proto3,oneof" json:"fragment,omitempty"`
}

func (x *DataStruct) Reset() {
	*x = DataStruct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datastruct_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataStruct) ProtoMessage() {}

func (x *DataStruct) ProtoReflect() protoreflect.Message {
	mi := &file_datastruct_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataStruct.ProtoReflect.Descriptor instead.
func (*DataStruct) Descriptor() ([]byte, []int) {
	return file_datastruct_proto_rawDescGZIP(), []int{1}
}

func (x *DataStruct) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DataStruct) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DataStruct) GetFragment() *FragmentInfo {
	if x != nil {
		return x.Fragment
	}
	return nil
}

var File_datastruct_proto protoreflect.FileDescriptor

var file_datastruct_proto_rawDesc = []byte{
	0x0a, 0x10, 0x64, 0x61, 0x74, 0x61, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x64, 0x0a, 0x0c, 0x46, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x72, 0x61, 0x67, 0x73, 0x65, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x66, 0x72, 0x61, 0x67, 0x73, 0x65, 0x74, 0x49,
	0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x69, 0x7a, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x7d, 0x0a, 0x0a, 0x44, 0x61, 0x74, 0x61,
	0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x2e, 0x0a, 0x08, 0x66, 0x72,
	0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x46,
	0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x08, 0x66,
	0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x66,
	0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x1b, 0x5a, 0x19, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x31, 0x33, 0x6e, 0x2d, 0x69, 0x6f, 0x2f, 0x6c, 0x6e,
	0x64, 0x61, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_datastruct_proto_rawDescOnce sync.Once
	file_datastruct_proto_rawDescData = file_datastruct_proto_rawDesc
)

func file_datastruct_proto_rawDescGZIP() []byte {
	file_datastruct_proto_rawDescOnce.Do(func() {
		file_datastruct_proto_rawDescData = protoimpl.X.CompressGZIP(file_datastruct_proto_rawDescData)
	})
	return file_datastruct_proto_rawDescData
}

var file_datastruct_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_datastruct_proto_goTypes = []interface{}{
	(*FragmentInfo)(nil), // 0: FragmentInfo
	(*DataStruct)(nil),   // 1: DataStruct
}
var file_datastruct_proto_depIdxs = []int32{
	0, // 0: DataStruct.fragment:type_name -> FragmentInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_datastruct_proto_init() }
func file_datastruct_proto_init() {
	if File_datastruct_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_datastruct_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FragmentInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datastruct_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataStruct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_datastruct_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_datastruct_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_datastruct_proto_goTypes,
		DependencyIndexes: file_datastruct_proto_depIdxs,
		MessageInfos:      file_datastruct_proto_msgTypes,
	}.Build()
	File_datastruct_proto = out.File
	file_datastruct_proto_rawDesc = nil
	file_datastruct_proto_goTypes = nil
	file_datastruct_proto_depIdxs = nil
}
